# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.4
  - 1.5
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.4
      script: julia --project=docs -e '
          using Pkg;
          pkg"add https://github.com/JuliaAtoms/AtomicLevels.jl.git";
          pkg"add https://github.com/JuliaAtoms/EnergyExpressions.jl.git";
          pkg"add HalfIntegers";
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate(); Pkg.add("Unitful");
          include("docs/make.jl");'
      after_success: skip
