name = "AngularMomentumAlgebra"
uuid = "0bb1b1ac-0216-11e9-361b-bb110c659ce1"
authors = ["Stefanos Carlström <stefanos.carlstrom@gmail.com>"]
version = "0.1.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"
